ROTORS_DATA = {
    "I":   {"map": "EKMFLGDQVZNTOWYHXUSPAIBRCJ", "notch": "Q"},
    "II":  {"map": "AJDKSIRUXBLHWTMCQGZNPYFVOE", "notch": "E"},
    "III": {"map": "BDFHJLCPRTXVZNYEIWGAKMUSQO", "notch": "V"}
}

REFLECTORS_DATA = {
    "B": "YRUHQSLDPXNGOKMIEBFZCWVJAT",
    "C": "FVPJIAOYEDRZXWGCTKUQSBNMHL"
}
